hydra-genetics/hydra-genetics

.github/PULL_REQUEST_TEMPLATE.md, hydra_genetics/pipeline-template/README.md
feat: pull-request template 
pull-request template which will make new pull-request more structured
=> Pull-request template

requirements.txt, setup.py
* Add automatic upload to pypi
=> dev to master

README.md, hydra_genetics/pipeline-template/.github/workflows/snakefmt.yaml, hydra_genetics/pipeline-template/config/units.tsv, hydra_genetics/pipeline-template/workflow/schemas/units.schema.yaml, hydra_genetics/rule-template/skeleton_rule.smk, hydra_genetics/utils/units.py, setup.py
- Update templates
- Update readme
=> Minor updates

hydra_genetics/pipeline-template/config/config.yaml, hydra_genetics/pipeline-template/config/resources.yaml, hydra_genetics/pipeline-template/requirements.txt, hydra_genetics/pipeline-template/workflow/schemas/resources.schema.yaml, hydra_genetics/rule-template/skeleton_rule.smk
Feat: Update resources section in templates
=> Feat: Update resources section in templates

hydra_genetics/utils/units.py, tests/utils/files/units_2.tsv, tests/utils/test_units.py
Fix: make sure a dataframe is returned
=> Fix: make sure a dataframe is returned

hydra_genetics/utils/units.py, tests/utils/files/units.tsv, tests/utils/files/units_2.tsv, tests/utils/test_units.py
Feat: function used to extract platforms from units.tsv file
=> Feat: function used to extract platforms from units.tsv file

hydra_genetics/__main__.py, hydra_genetics/commands/create.py
feat: new command line option to generate samples.tsv and units.tsv files.
Needs unit test.
=> create inpute file tool.

.gitignore, hydra_genetics/__main__.py, hydra_genetics/commands/create.py, hydra_genetics/pipeline-template/workflow/rules/common.smk, hydra_genetics/utils/io/chr.py, hydra_genetics/utils/io/filtered_mutations.py, hydra_genetics/utils/io/hotspot.py, hydra_genetics/utils/io/multibp.py, hydra_genetics/utils/io/utils.py, hydra_genetics/utils/models/hotspot.py, hydra_genetics/utils/units.py, setup.py, tests/utils/files/report_columns.yaml, tests/utils/files/report_columns_vep.yaml, tests/utils/files/units.tsv, tests/utils/files/units_2.tsv, tests/utils/io/test_filtered_mutations.py, tests/utils/io/test_hotspot.py, tests/utils/models/test_hotspot.py, tests/utils/test_units.py
feat: filtered mutations libraries
=> more libraries

setup.py
=> minor update

hydra_genetics/utils/io/hotspot_report.py, tests/utils/files/report_columns_vep_hide_column.yaml, tests/utils/files/report_columns_vep_order_output.yaml, tests/utils/io/test_mutations_report.py
This pull-request add features to hotspot_report generation, making it more flexible 
Added: make it possible to set output order and hide columns
=> Hotspot report update

hydra_genetics/__main__.py, hydra_genetics/commands/create.py, hydra_genetics/utils/io/hotspot.py
feat: extract run information from fastq files, machine id, flowcell, lane and barcode
=> Add functionality generate units

hydra_genetics/commands/create.py
=> fix: bug that overwrites dict

README.md, hydra_genetics/pipeline-template/workflow/rules/common.smk, setup.py
=> fix: bug fix

hydra_genetics/commands/create.py, setup.py
=> fix: handle sample name correct

.github/workflows/conventional-prs.yml
=> fix: correct syntax for conventional-prs workflow

.github/workflows/release-please.yaml
=> fix: fix invalid syntax in releas-please workflow

.github/workflows/conventional-prs.yml, .github/workflows/release-please.yaml
=> fix: correct invalid syntax in releas-please workflow

.github/workflows/release-please.yaml
=> fix: change-package name and set default-branch.

.github/workflows/release-please.yaml
=> fix: update package name and change default-branch

hydra_genetics/pipeline-template/.github/workflows/conventional-prs.yml
=> feat: add workflow for semantic check to template

hydra_genetics/pipeline-template/requirements.txt
=> feat: update hydra-genetics requirements in template to 0.3.0

.github/workflows/release-please.yaml, hydra_genetics/pipeline-template/.github/workflows/conventional-prs.yml, hydra_genetics/pipeline-template/requirements.txt
=> feat: update pipeline/module template

hydra_genetics/commands/create.py
=> fix: use correct dict variable name

hydra_genetics/pipeline-template/.github/workflows/conventional-prs.yml
=> fix: escape curly brackets in conventional-prs workflow.

hydra_genetics/pipeline-template/workflow/schemas/resources.schema.yaml
=> fix: set correct indentation for resources.schema.yaml

hydra_genetics/pipeline-template/workflow/schemas/config.schema.yaml
=> fix: set correct indentation for config.schema.yaml

.github/workflows/testrun-commands.yaml
=> fix: change name of testrun-commands workflow

hydra_genetics/utils/io/hotspot_report.py, hydra_genetics/utils/io/utils.py
=> feat: return None with missing/empty annotation data

hydra_genetics/commands/create.py, hydra_genetics/pipeline-template/config/samples.tsv, hydra_genetics/pipeline-template/config/units.tsv, hydra_genetics/pipeline-template/workflow/rules/common.smk, hydra_genetics/pipeline-template/workflow/schemas/samples.schema.yaml, hydra_genetics/pipeline-template/workflow/schemas/units.schema.yaml, hydra_genetics/utils/units.py, tests/utils/files/samples.tsv, tests/utils/files/units.tsv, tests/utils/files/units_2.tsv, tests/utils/test_samples.py, tests/utils/test_units.py
=> refactor: change column name run in units to flowcell.

requirements.test.txt
=> feat: clean test requirements

hydra_genetics/utils/io/hotspot_report.py, tests/utils/files/report_columns_combine_columns.yaml, tests/utils/files/report_columns_combine_columns_multi_level.yaml, tests/utils/io/test_mutations_report.py
=> feat: make it possible to combine columns in hotspot report.

hydra_genetics/commands/create.py
=> fix: change TC to tumor_content

hydra_genetics/utils/io/hotspot_report.py
=> feat: make it possible to change depth field

hydra_genetics/commands/create.py, hydra_genetics/utils/io/hotspot_report.py
=> chore: dev to master

hydra_genetics/utils/io/hotspot_report.py
=> fix: add gcvf_depth_field to other variants and found hotspot variants

hydra_genetics/utils/models/hotspot.py
=> refactor: spelling typo

hydra_genetics/commands/create.py, hydra_genetics/pipeline-template/.github/PULL_REQUEST_TEMPLATE.md, hydra_genetics/pipeline-template/.github/workflows/conventional-prs.yml, hydra_genetics/pipeline-template/.github/workflows/integration1.yaml, hydra_genetics/pipeline-template/.github/workflows/lint.yaml, hydra_genetics/pipeline-template/.github/workflows/release-please.yaml, hydra_genetics/pipeline-template/.github/workflows/snakefmt.yaml, hydra_genetics/pipeline-template/.github/workflows/snakemake-dry-run.yaml, hydra_genetics/pipeline-template/.tests/integration/config.yaml, hydra_genetics/pipeline-template/README.md, hydra_genetics/pipeline-template/config/config.yaml, hydra_genetics/pipeline-template/requirements.test.txt, hydra_genetics/pipeline-template/requirements.txt, hydra_genetics/pipeline-template/workflow/Snakefile, hydra_genetics/pipeline-template/workflow/rules/common.smk, hydra_genetics/pipeline-template/workflow/schemas/samples.schema.yaml, hydra_genetics/rule-template/skeleton_rule.smk
=> fix: update to comply with latest guidelines

hydra_genetics/utils/units.py, tests/utils/files/units_2.tsv, tests/utils/test_units.py
=> fix: added barcode to get_unit filter

hydra_genetics/pipeline-template/workflow/rules/common.smk
=> fix: add barcode as index

hydra_genetics/commands/create.py
=> fix: exit of no files are found

hydra_genetics/utils/io/hotspot_report.py
=> refactor: remove code that never will be executed

hydra_genetics/__init__.py, hydra_genetics/exceptions.py
=> feat: add function used to set min version for hydra-genetics

hydra_genetics/utils/misc.py, tests/utils/test_misc.py
=> fix: patch extract chr

hydra_genetics/pipeline-template/requirements.txt
=> fix: default for extract_chr if file doesn't exist

hydra_genetics/pipeline-template/workflow/rules/common.smk
=> feat: make config.yaml location more flexible

hydra_genetics/pipeline-template/workflow/rules/common.smk
=> feat: make configfile/configfiles argument mandatory

hydra_genetics/pipeline-template/.github/workflows/integration1.yaml, hydra_genetics/pipeline-template/.github/workflows/lint.yaml, hydra_genetics/pipeline-template/.github/workflows/snakemake-dry-run.yaml
=> feat: fix template for github actions

hydra_genetics/commands/create.py
=> fix: handle bug the arise when specifying output folder

hydra_genetics/utils/io/hotspot_report.py, tests/utils/files/report_columns_combine_columns.yaml, tests/utils/io/test_mutations_report.py
=> feat: make it possible to format string and values

hydra_genetics/__main__.py, hydra_genetics/commands/create.py
=> fix: make it possible to set a default barcode

hydra_genetics/utils/io/hotspot_report.py
=> fix: handle hotspot formatting errors better

hydra_genetics/utils/io/hotspot_report.py
=> fix: update handling of formatting of report values

hydra_genetics/rule-template/skeleton_rule.smk
=> fix: skeleton rule to pass snakefmt

hydra_genetics/utils/io/hotspot_report.py, hydra_genetics/utils/models/hotspot.py, tests/utils/files/report_columns_select_column.yaml, tests/utils/io/test_mutations_report.py
* add "select_first" option, which will make select the first data source specified if it has data
else it will select the remaining data sources
* add "if_first_exist" option, which will select all except the first data source if the first data
source has data
=> feat: make it possible to select one ore more of specified data sources

hydra_genetics/utils/io/hotspot_report.py
=> fix(utils): update handling for retrieval of data using function

hydra_genetics/utils/misc.py, requirements.test.txt
=> feat: function used to switch between github and local repos

hydra_genetics/__main__.py
- name must start with a small letter
- name can contain numbers
=> feat(comman): update workflow name regex

hydra_genetics/pipeline-template/.github/workflows/integration.yaml, hydra_genetics/pipeline-template/.github/workflows/lint.yaml, hydra_genetics/pipeline-template/.github/workflows/pycodestyle.yaml, hydra_genetics/pipeline-template/.github/workflows/pytest.yaml, hydra_genetics/pipeline-template/.github/workflows/snakemake-dry-run.yaml
=> feat: update project template

hydra_genetics/utils/io/utils.py
=> feat!: force user to set index from which format field data will be extracted

hydra_genetics/utils/io/hotspot_report.py
=> refactor: remove unused code

hydra_genetics/commands/create.py, hydra_genetics/pipeline-template/.github/workflows/integration.yaml, hydra_genetics/pipeline-template/workflow/Snakefile, hydra_genetics/pipeline-template/workflow/envs/dummy.yaml, hydra_genetics/rule-template/skeleton_env.yaml, hydra_genetics/rule-template/skeleton_rule.smk
=> feat: drop conda support and testing

hydra_genetics/__main__.py, hydra_genetics/commands/prep_pipeline_env.py
=> feat: cli to fetch containers and update config

hydra_genetics/pipeline-template/requirements.txt
=> fix: update requirements for pipeline template

.github/CODEOWNERS
=> docs: remove martin as code owner

hydra_genetics/pipeline-template/config/config.yaml
=> fix: config template

requirements.test.txt, setup.py
=> feat: update click dep to match snakefmt versions

hydra_genetics/commands/prep_pipeline_env.py
=> fix: change to correct parameter name

hydra_genetics/pipeline-template/config/config.yaml, hydra_genetics/pipeline-template/config/output_files.json, hydra_genetics/pipeline-template/config/units.tsv, hydra_genetics/pipeline-template/workflow/Snakefile, hydra_genetics/pipeline-template/workflow/rules/common.smk, hydra_genetics/pipeline-template/workflow/schemas/config.schema.yaml, hydra_genetics/pipeline-template/workflow/schemas/output_files.schema.yaml, hydra_genetics/pipeline-template/workflow/schemas/units.schema.yaml
=> feat: output list/rule copy function added.

hydra_genetics/pipeline-template/workflow/schemas/units.schema.yaml
=> fix: add barcode to units schema

hydra_genetics/pipeline-template/workflow/schemas/units.schema.yaml
=> refactor: update units.schema.yaml for pipeline template

hydra_genetics/pipeline-template/workflow/schemas/units.schema.yaml
=> refactor: Update units.schema.yaml

hydra_genetics/commands/create.py
=> fix: add abs path template for png copying

docs/simple_pipeline.md
=> docs: update tutorial

hydra_genetics/pipeline-template/requirements.txt
=> feat: update hydra-genetics version for template

hydra_genetics/pipeline-template/workflow/rules/common.smk
=> fix: add missing library name and update variable name

docs/simple_pipeline.md
=> docs: add command to download reference and fastq data from gdrive

hydra_genetics/pipeline-template/workflow/rules/common.smk
=> fix: update output list function

docs/simple_pipeline.md
=> docs: add missing \ to tutorial command

docs/simple_pipeline.md
=> docs: download test data later

hydra_genetics/rule-template/skeleton_rule.smk
=> docs: Update skeleton_rule.smk message

hydra_genetics/commands/prep_pipeline_env.py
=> fix: cli spelling error

hydra_genetics/pipeline-template/requirements.txt
=> feat: update snakemake versionm allow range up to version 8

hydra_genetics/commands/create.py
=> feat: for pipeline template, change branch name master to main

hydra_genetics/pipeline-template/.github/workflows/snakefmt.yaml
=> fix: update snakefmt workflow to match latest template

hydra_genetics/pipeline-template/.github/workflows/lint.yaml
=> fix: update lint workflow to match current template

hydra_genetics/pipeline-template/workflow/rules/common.smk
=> fix: make style check happy with regex in template for common.smk

hydra_genetics/pipeline-template/README.md
=> fix: update test links in template

docs/config.md, docs/profile.md, docs/simple_pipeline.md, docs/testing.md, hydra_genetics/pipeline-template/.github/workflows/integration.yaml, hydra_genetics/pipeline-template/.github/workflows/lint.yaml, hydra_genetics/pipeline-template/.github/workflows/pycodestyle.yaml, hydra_genetics/pipeline-template/.github/workflows/pytest.yaml, hydra_genetics/pipeline-template/.github/workflows/release-please.yaml, hydra_genetics/pipeline-template/.github/workflows/snakemake-dry-run.yaml, hydra_genetics/pipeline-template/.tests/integration/config/config.yaml, hydra_genetics/pipeline-template/.tests/integration/config/output_files.yaml, hydra_genetics/pipeline-template/README.md, hydra_genetics/pipeline-template/config/config.yaml, hydra_genetics/pipeline-template/workflow/rules/common.smk
=> test: update pipeline template integration config

hydra_genetics/pipeline-template/workflow/rules/common.smk
=> fix: add sys.exit if no --configfile

hydra_genetics/commands/references.py, hydra_genetics/utils/io/reference.py
=> fix: handle case when array or number is passed to is_file

hydra_genetics/commands/references.py, hydra_genetics/utils/io/reference.py
=> fix: improve validation

hydra_genetics/pipeline-template/.readthedocs.yaml
=> fix: update readthedocs with correct mkdocs,yaml file name

hydra_genetics/commands/prep_pipeline_env.py, hydra_genetics/commands/references.py, hydra_genetics/utils/io/reference.py
=> fix: minor bug fixes

hydra_genetics/pipeline-template/workflow/rules/common.smk
=> fix: remove conda from template

hydra_genetics/utils/io/reference.py
these entries are only used to validate the data, i.e used for when local copies exist.
=> feat: make it possible to entries without url when fetching data

README.md, docs/modules.md
=> docs: update rtd links

.github/workflows/testrun-commands.yaml, hydra_genetics/commands/references.py, hydra_genetics/utils/io/reference.py, tests/utils/files/references_config.yaml, tests/utils/files/references_divided_file_config.yaml, tests/utils/files/references_divided_file_fetch.yaml, tests/utils/files/references_fetch.yaml, tests/utils/files/validation.json, tests/utils/files/validation.yaml
=> feat: update reference fetching

hydra_genetics/utils/io/reference.py
=> refactor: simplify code and add more logging

hydra_genetics/utils/io/reference.py
=> refactor: add more logging messages

hydra_genetics/utils/io/reference.py
=> refactor: remove print statment

hydra_genetics/utils/io/reference.py
=> fix: parent folder bug and remove existing folder if it needs updating

hydra_genetics/utils/io/reference.py
=> refactor: add more logging

hydra_genetics/commands/references.py, hydra_genetics/utils/io/reference.py
=> feat: output more information about download/validation for ref files

hydra_genetics/utils/misc.py, tests/utils/files/config_variable_replacement.yaml, tests/utils/test_misc.py
=> feat: function used to add variable options to a yaml file

hydra_genetics/utils/io/reference.py
=> fix: reduce memory usage when downloading files

hydra_genetics/commands/references.py, hydra_genetics/utils/io/reference.py, tests/utils/files/references_fetch.yaml
=> feat: make it possible to define links handling fetching data

hydra_genetics/commands/references.py, hydra_genetics/utils/io/reference.py
=> fix: remove code

docs/simple_pipeline.md
=> docs: update hydra-genetics version for simple pipeline

.github/workflows/test-build-mkdocs.yaml, docs/requirements.txt, hydra_genetics/pipeline-template/.github/workflows/test-build-mkdocs, hydra_genetics/pipeline-template/docs/requirements.txt
=> feat: add test build mkdocs to template

hydra_genetics/utils/io/reference.py
=> fix: handle events when a file is listed multiple times in the config

docs/simple_pipeline.md, hydra_genetics/pipeline-template/requirements.txt
=> docs: update hydra-genetics version in docs and templates

.github/workflows/test-build-for-pip.yaml
=> ci: remove if statements

hydra_genetics/utils/misc.py
=> fix: handle list of str when replacing config variables

.github/workflows/test-build-for-pip.yaml
=> ci: update test build workflow

hydra_genetics/utils/io/hotspot_report.py, hydra_genetics/utils/io/utils.py
=> fix: bug in vep annotation handling

hydra_genetics/utils/io/utils.py
=> fix: return None when empty string in vep annotation

hydra_genetics/__main__.py
=> refactor: output default values when using --help

hydra_genetics/utils/io/hotspot_report.py, hydra_genetics/utils/io/utils.py, tests/utils/io/test_mutations_report.py
=> perf: improve performance and fix minor issue

hydra_genetics/pipeline-template/.github/workflows/snakefmt.yaml, hydra_genetics/pipeline-template/requirements.txt
=> feat: update snakefmt linter version for pipeline template

.tests/integration/samples_and_settings.json, hydra_genetics/commands/create.py
=> fix: match latest settings format

hydra_genetics/commands/create.py
=> fix: handle tumour content set to 0 when creating sample.tsv

hydra_genetics/utils/io/reference.py
=> feat: update handling of reference files

docs/development/help_code.md, hydra_genetics/__init__.py, hydra_genetics/pipeline-template/requirements.txt, hydra_genetics/pipeline-template/workflow/rules/common.smk, hydra_genetics/utils/misc.py, hydra_genetics/utils/software_versions.py
=> docs: add missing variable to example

docs/development/help_code.md, hydra_genetics/pipeline-template/workflow/rules/common.smk
=> docs: change filename

docs/development/help_code.md
=> docs: update import from tool versions

hydra_genetics/pipeline-template/workflow/schemas/units.schema.yaml
=> feat: Update units.schema.yaml for long read

hydra_genetics/commands/create.py
=> fix: fix typo in warning message

hydra_genetics/pipeline-template/workflow/rules/common.smk
- remove trailing version from path results/versions/software_version
- always pipeline version file to multiqc
=> fix: minor updates to pipeline template

hydra_genetics/utils/software_versions.py
=> fix(utils): change container re search pattern

.github/workflows/release-please.yaml
=> ci: add token to make it possible for please-release to run actions

README.md
=> docs: add badge for mkdocs

.github/workflows/release-please.yaml
=> ci: update release please

hydra_genetics/utils/software_versions.py
Handles duplicate items in the list which occurs when the same container appears more than once in the config.
=> fix: convert name_list to set to remove duplicate items

hydra_genetics/utils/software_versions.py
=> fix: filter more one docker labels

docs/development/help_code.md, hydra_genetics/utils/software_versions.py
=> feat: output software versions into one file 

hydra_genetics/utils/io/hotspot_report.py, tests/utils/io/test_mutations_report.py
=> feat: report all region_all variants in cov_and_mut

hydra_genetics/utils/software_versions.py
=> fix: handle remote on local file the same

.github/workflows/testrun-commands.yaml
=> fix: update python action

.github/workflows/main.yaml, .github/workflows/test-build-for-pip.yaml
=> test: update depricated github action to v3

hydra_genetics/pipeline-template/.github/workflows/pycodestyle.yaml
=> fix: update pycodestyle actions

hydra_genetics/pipeline-template/.github/workflows/integration.yaml, hydra_genetics/pipeline-template/.github/workflows/pycodestyle.yaml, hydra_genetics/pipeline-template/.github/workflows/pytest.yaml
This pull request also remove the installation of the requirements.test.txt which are not needed for the integration test
Also updates actions to v3:
actions/checkout@v2 --> actions/checkout@v3
actions/setup-python@v2 --> actions/setup-python@v3
=> fix(pipeline-template): remove conda/mamba from the integration template

build/README.md, build/build_conda.sh, docs/packaging_pipeline/unpack_pipeline.md
=> feat: update build_conda.sh

docs/packaging_pipeline/package_pipeline.md
=> docs: link to the build script
